apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: eetape/weatherservice:latest
          ports:
            - containerPort: 8000
          env:
            - name: OPENCAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opencage-api-key
                  key: OPENCAGE_API_KEY
